name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - "master"
      - "develop"
    tags-ignore:
      - "**"
    paths-ignore:
      - "docs/**"
      - "bamboo/**"
      - "README.rst"

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]


jobs:

  # Build downstream packages on HPC
  downstream-ci-hpc:
    name: downstream-ci-hpc
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ecmwf/downstream-ci/.github/workflows/downstream-ci-hpc.yml@use-test-user
    with:
      ecbuild: ecmwf/ecbuild@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

#Â DISABLED FOR NOW UNTIL REPO IS SET UP FOR THIS
#  notify:
#    runs-on: ubuntu-latest
#    needs:
#      - downstream-ci
#      - private-downstream-ci
#      - downstream-ci-hpc
#      - private-downstream-ci-hpc
#    if: ${{ always() && !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
#    steps:
#      - name: Trigger Teams notification
#        uses: ecmwf/notify-teams@v1
#        with:
#          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
#          needs_context: ${{ toJSON(needs) }}
