name: sync

# Controls when the workflow will run
on:

  # Trigger the workflow on all pushes
  push:
    branches:
    - '**'
    tags:
    - '**'

  # Trigger the workflow when a branch or tag is deleted
  delete: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:

  # Calls a reusable CI workflow to sync the current with a remote repository.
  #   It will correctly handle addition of any new and removal of existing Git objects.
  sync:
    name: sync
    uses: ecmwf/reusable-workflows/.github/workflows/sync.yml@v1
    secrets:
      target_repository: ecsdk/ecbuild
      target_username: ClonedDuck
      target_token: ${{ secrets.BITBUCKET_PAT }}
